//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attendence_sys_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Grade1 { get; set; }
        public Nullable<int> TotalDaysAttended { get; set; }
        public Nullable<System.DateTime> GradePeriodStartDate { get; set; }
        public Nullable<System.DateTime> GradePeriodEndDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
